# Form implementation generated from reading ui file 'player_merged.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 630)
        MainWindow.setStyleSheet("#MainWindow {\n"
"        background-color: #fff;\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon_only_widget = QtWidgets.QWidget(parent=self.page_2)
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5.addWidget(self.icon_only_widget)
        self.full_menu_widget = QtWidgets.QWidget(parent=self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_menu_widget.sizePolicy().hasHeightForWidth())
        self.full_menu_widget.setSizePolicy(sizePolicy)
        self.full_menu_widget.setStyleSheet("#full_menu_widget {\n"
"        background-color: #E0E0E0;\n"
"        border-radius: 7px;\n"
"    }\n"
"\n"
"    /* style for QPushButton */\n"
"    #full_menu_widget QPushButton {\n"
"        border:none;\n"
"        border-radius: 3px;\n"
"        text-align: left;\n"
"        padding: 8px 0 8px 15px;\n"
"        color: #788596;\n"
"    }\n"
"\n"
"    #full_menu_widget QPushButton:hover {\n"
"        background-color: rgba( 86, 101, 115, 0.5);\n"
"    }\n"
"\n"
"    #full_menu_widget QPushButton:checked {\n"
"        color: rgb(0, 0, 0);\n"
"        font-size: 16px;\n"
"        icon-size: 32px 32px;\n"
"    }\n"
"\n"
"    /* style for logo image */\n"
"    #logo_label_2 {\n"
"        padding: 5px;\n"
"        color: #fff;\n"
"    }\n"
"\n"
"    /* style for APP title */\n"
"    #logo_label_3 {\n"
"        padding-right: 10px;\n"
"        color: rgb(0, 0, 0);\n"
"    }")
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logo = QtWidgets.QPushButton(parent=self.full_menu_widget)
        self.logo.setEnabled(False)
        self.logo.setStyleSheet("#logo{\n"
"        padding: 5px;\n"
"        color: #fff;\n"
"        text-align: center;\n"
"    }\n"
"logo:disabled {\n"
"        padding: 5px;\n"
"        color: #fff;\n"
"        text-align: center;\n"
"    }")
        self.logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui_icons/player.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logo.setIcon(icon)
        self.logo.setIconSize(QtCore.QSize(32, 32))
        self.logo.setObjectName("logo")
        self.verticalLayout_4.addWidget(self.logo)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.logo_label_3 = QtWidgets.QLabel(parent=self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.logo_label_3.setStyleSheet("#logo_label{\n"
"    text-align: center;\n"
"}")
        self.logo_label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo_label_3.setObjectName("logo_label_3")
        self.verticalLayout_4.addWidget(self.logo_label_3)
        spacerItem = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scan_btn_2 = QtWidgets.QPushButton(parent=self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.scan_btn_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ui_icons/recent_icon_148510.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.scan_btn_2.setIcon(icon1)
        self.scan_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.scan_btn_2.setCheckable(True)
        self.scan_btn_2.setAutoExclusive(True)
        self.scan_btn_2.setObjectName("scan_btn_2")
        self.verticalLayout_2.addWidget(self.scan_btn_2)
        self.ai_btn_2 = QtWidgets.QPushButton(parent=self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.ai_btn_2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ui_icons/list-symbol-of-three-items-with-dots_icon-icons.com_72994.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ai_btn_2.setIcon(icon2)
        self.ai_btn_2.setIconSize(QtCore.QSize(20, 20))
        self.ai_btn_2.setCheckable(True)
        self.ai_btn_2.setAutoExclusive(True)
        self.ai_btn_2.setObjectName("ai_btn_2")
        self.verticalLayout_2.addWidget(self.ai_btn_2)
        self.ai_btn_4 = QtWidgets.QPushButton(parent=self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.ai_btn_4.setFont(font)
        self.ai_btn_4.setIcon(icon2)
        self.ai_btn_4.setIconSize(QtCore.QSize(20, 20))
        self.ai_btn_4.setCheckable(True)
        self.ai_btn_4.setAutoExclusive(True)
        self.ai_btn_4.setObjectName("ai_btn_4")
        self.verticalLayout_2.addWidget(self.ai_btn_4)
        self.ai_btn_5 = QtWidgets.QPushButton(parent=self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.ai_btn_5.setFont(font)
        self.ai_btn_5.setIcon(icon2)
        self.ai_btn_5.setIconSize(QtCore.QSize(20, 20))
        self.ai_btn_5.setCheckable(True)
        self.ai_btn_5.setAutoExclusive(True)
        self.ai_btn_5.setObjectName("ai_btn_5")
        self.verticalLayout_2.addWidget(self.ai_btn_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 373, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frame_5 = QtWidgets.QFrame(parent=self.full_menu_widget)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings = QtWidgets.QPushButton(parent=self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.settings.setFont(font)
        self.settings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settings.setStyleSheet("QPushButton {\n"
"        padding: 0px;             /* Add padding on all sides */\n"
"    }")
        self.settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ui_icons/settingscog_87317.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings.setIcon(icon3)
        self.settings.setIconSize(QtCore.QSize(20, 20))
        self.settings.setCheckable(True)
        self.settings.setAutoExclusive(True)
        self.settings.setObjectName("settings")
        self.horizontalLayout.addWidget(self.settings)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.about = QtWidgets.QPushButton(parent=self.frame_5)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.about.setStyleSheet("QPushButton {\n"
"        padding: 0px;             /* Add padding on all sides */\n"
"    }\n"
"")
        self.about.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ui_icons/4213426-about-description-help-info-information-notification_115427.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.about.setIcon(icon4)
        self.about.setIconSize(QtCore.QSize(20, 20))
        self.about.setObjectName("about")
        self.horizontalLayout.addWidget(self.about)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.help = QtWidgets.QPushButton(parent=self.frame_5)
        self.help.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.help.setStyleSheet("QPushButton {\n"
"        padding: 0px;             /* Add padding on all sides */\n"
"    }")
        self.help.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ui_icons/Help_icon-icons.com_55891.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.help.setIcon(icon5)
        self.help.setIconSize(QtCore.QSize(25, 25))
        self.help.setObjectName("help")
        self.horizontalLayout.addWidget(self.help)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(parent=self.full_menu_widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addWidget(self.full_menu_widget)
        self.widget_3 = QtWidgets.QWidget(parent=self.page_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget = QtWidgets.QWidget(parent=self.widget_3)
        self.widget.setMinimumSize(QtCore.QSize(0, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.greeting_label = QtWidgets.QLabel(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.greeting_label.sizePolicy().hasHeightForWidth())
        self.greeting_label.setSizePolicy(sizePolicy)
        self.greeting_label.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        self.greeting_label.setFont(font)
        self.greeting_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.greeting_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greeting_label.setObjectName("greeting_label")
        self.horizontalLayout_4.addWidget(self.greeting_label)
        spacerItem5 = QtWidgets.QSpacerItem(236, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.user__btn = QtWidgets.QPushButton(parent=self.widget)
        self.user__btn.setStyleSheet("background-color: transparent;")
        self.user__btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/account.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.user__btn.setIcon(icon6)
        self.user__btn.setIconSize(QtCore.QSize(32, 32))
        self.user__btn.setObjectName("user__btn")
        self.horizontalLayout_4.addWidget(self.user__btn)
        self.verticalLayout_5.addWidget(self.widget)
        self.mainStack = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.mainStack.setObjectName("mainStack")
        self.streamPage = QtWidgets.QWidget()
        self.streamPage.setObjectName("streamPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.streamPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.streamPage)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.stream_url = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stream_url.setFont(font)
        self.stream_url.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.stream_url.setInputMask("")
        self.stream_url.setText("")
        self.stream_url.setObjectName("stream_url")
        self.horizontalLayout_6.addWidget(self.stream_url)
        self.clearURL_btn = QtWidgets.QPushButton(parent=self.frame)
        self.clearURL_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.clearURL_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.clearURL_btn.setFont(font)
        self.clearURL_btn.setStyleSheet("QPushButton#clearURL_btn {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(33, 150, 243, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#clearURL_btn:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(63, 81, 181, 219), stop:1 rgba(103, 58, 183, 226));\n"
"}\n"
"\n"
"QPushButton#clearURL_btn:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(103, 58, 183, 255);\n"
"}\n"
"QPushButton#clearURL_btn:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"\n"
"")
        self.clearURL_btn.setObjectName("clearURL_btn")
        self.horizontalLayout_6.addWidget(self.clearURL_btn)
        self.startStream_btn = QtWidgets.QPushButton(parent=self.frame)
        self.startStream_btn.setMinimumSize(QtCore.QSize(50, 0))
        self.startStream_btn.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.startStream_btn.setFont(font)
        self.startStream_btn.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.startStream_btn.setStyleSheet("QPushButton#startStream_btn {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(33, 150, 243, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#startStream_btn:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(63, 81, 181, 219), stop:1 rgba(103, 58, 183, 226));\n"
"}\n"
"\n"
"QPushButton#startStream_btn:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(103, 58, 183, 255);\n"
"}\n"
"\n"
"QPushButton#startStream_btn:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        self.startStream_btn.setObjectName("startStream_btn")
        self.horizontalLayout_6.addWidget(self.startStream_btn)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.streamPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.secondaryStack1 = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.secondaryStack1.setStyleSheet("")
        self.secondaryStack1.setObjectName("secondaryStack1")
        self.fileBrowser = QtWidgets.QWidget()
        self.fileBrowser.setObjectName("fileBrowser")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fileBrowser)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_8 = QtWidgets.QFrame(parent=self.fileBrowser)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_8.setStyleSheet("#frame_8 {\n"
"        background-color: #E0E0E0;\n"
"        border-radius: 7px;\n"
"    }")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.streamServices = QtWidgets.QFrame(parent=self.frame_8)
        self.streamServices.setMaximumSize(QtCore.QSize(200, 16777215))
        self.streamServices.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.streamServices.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.streamServices.setObjectName("streamServices")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.streamServices)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.streamServices)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.streamServices)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 8px; /* Thinner vertical scrollbar */\n"
"    margin: 2px 0 2px 0;\n"
"    border-radius: 10px; /* Rounded ends */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgba(128, 128, 128, 0.7); /* Grey handle */\n"
"    border-radius: 4px; /* Rounded handle */\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: rgba(96, 96, 96, 1); /* Darker grey when hovered */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 8px; /* Thinner horizontal scrollbar */\n"
"    margin: 0 2px 0 2px;\n"
"    border-radius: 10px; /* Rounded ends */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgba(128, 128, 128, 0.7); /* Grey handle */\n"
"    border-radius: 10px; /* Rounded handle */\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: rgba(96, 96, 96, 1); /* Darker grey when hovered */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: none;\n"
"    height: 0px;\n"
"    width: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: transparent;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 172, 484))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.onedrive = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.onedrive.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.onedrive.setFont(font)
        self.onedrive.setStyleSheet("QPushButton#onedrive {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#onedrive:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#onedrive:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#onedrive:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/onedrive.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.onedrive.setIcon(icon7)
        self.onedrive.setIconSize(QtCore.QSize(32, 32))
        self.onedrive.setObjectName("onedrive")
        self.verticalLayout_9.addWidget(self.onedrive)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem6)
        self.gdrive = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.gdrive.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.gdrive.setFont(font)
        self.gdrive.setStyleSheet("QPushButton#gdrive {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#gdrive:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#gdrive:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#gdrive:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/gdrive.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.gdrive.setIcon(icon8)
        self.gdrive.setIconSize(QtCore.QSize(32, 32))
        self.gdrive.setObjectName("gdrive")
        self.verticalLayout_9.addWidget(self.gdrive)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem7)
        self.box = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.box.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.box.setFont(font)
        self.box.setStyleSheet("QPushButton#box {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#box:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#box:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#box:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/box.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.box.setIcon(icon9)
        self.box.setIconSize(QtCore.QSize(32, 32))
        self.box.setObjectName("box")
        self.verticalLayout_9.addWidget(self.box)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem8)
        self.dropbox = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.dropbox.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.dropbox.setFont(font)
        self.dropbox.setStyleSheet("QPushButton#dropbox {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#dropbox:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#dropbox:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#dropbox:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/dropbox.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dropbox.setIcon(icon10)
        self.dropbox.setIconSize(QtCore.QSize(32, 32))
        self.dropbox.setObjectName("dropbox")
        self.verticalLayout_9.addWidget(self.dropbox)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem9)
        self.youtube = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.youtube.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.youtube.setFont(font)
        self.youtube.setStyleSheet("QPushButton#youtube {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#youtube:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#youtube:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#youtube:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/yt.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.youtube.setIcon(icon11)
        self.youtube.setIconSize(QtCore.QSize(32, 32))
        self.youtube.setObjectName("youtube")
        self.verticalLayout_9.addWidget(self.youtube)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_9.addItem(spacerItem10)
        self.localhost = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.localhost.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.localhost.setFont(font)
        self.localhost.setStyleSheet("QPushButton#localhost {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 183, 77, 219), stop:1 rgba(156, 39, 176, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton#localhost:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(255, 145, 0, 219), stop:1 rgba(123, 31, 162, 226));\n"
"}\n"
"\n"
"QPushButton#localhost:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(123, 31, 162, 255);\n"
"}\n"
"\n"
"QPushButton#localhost:disabled {\n"
"    background-color: rgba(200, 200, 200, 150);\n"
"    color: rgba(255, 255, 255, 150);\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/976598-appliances-case-computer-computer-tower-desktop-pc_106551.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.localhost.setIcon(icon12)
        self.localhost.setIconSize(QtCore.QSize(32, 32))
        self.localhost.setObjectName("localhost")
        self.verticalLayout_9.addWidget(self.localhost)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_9.addWidget(self.streamServices)
        self.browser = QtWidgets.QFrame(parent=self.frame_8)
        self.browser.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.browser.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.browser.setObjectName("browser")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.browser)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.stack2_3 = QtWidgets.QStackedWidget(parent=self.browser)
        self.stack2_3.setObjectName("stack2_3")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.stack2_3.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stack2_3.addWidget(self.page_4)
        self.verticalLayout_10.addWidget(self.stack2_3)
        self.horizontalLayout_9.addWidget(self.browser)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.secondaryStack1.addWidget(self.fileBrowser)
        self.recentsPage = QtWidgets.QWidget()
        self.recentsPage.setObjectName("recentsPage")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.recentsPage)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_9 = QtWidgets.QFrame(parent=self.recentsPage)
        self.frame_9.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.secondaryStack1.addWidget(self.recentsPage)
        self.noActivity = QtWidgets.QWidget()
        self.noActivity.setObjectName("noActivity")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.noActivity)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(parent=self.noActivity)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.secondaryStack1.addWidget(self.noActivity)
        self.verticalLayout_7.addWidget(self.secondaryStack1)
        self.verticalLayout_6.addWidget(self.frame_2)
        self.mainStack.addWidget(self.streamPage)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.mainStack.addWidget(self.page_5)
        self.verticalLayout_5.addWidget(self.mainStack)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_2 = QtWidgets.QWidget(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_11.addWidget(self.widget_2)
        self.frame_10 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 28))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_4.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.frame_10)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 18))
        self.horizontalSlider.setStyleSheet("QSlider {\n"
"        background: #f0f0f0;  /* Light grey background, almost white */\n"
"        height: 6px;  /* Slightly thinner slider */\n"
"        border-radius: 6px;  /* Less rounded edges for the whole slider */\n"
"    }\n"
"\n"
"    QSlider::groove:horizontal {\n"
"        border: none;\n"
"        background: #e0e0e0;  /* Light grey groove */\n"
"        height: 6px;\n"
"        border-radius: 6px;  /* Less curved ends for the groove */\n"
"    }\n"
"\n"
"    QSlider::sub-page:horizontal {\n"
"        background: #d0d0d0;  /* Slightly darker grey for the filled part */\n"
"        border-radius: 6px;  /* Less curved ends for the filled part */\n"
"    }\n"
"\n"
"    QSlider::add-page:horizontal {\n"
"        background: #e0e0e0;  /* Same light grey for the unfilled part */\n"
"        border-radius: 6px;  /* Less curved ends for the unfilled part */\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal {\n"
"        background: #ffffff;  /* White handle */\n"
"        border: 2px solid #b0b0b0;  /* Grey border around the handle */\n"
"        width: 14px;  /* Smaller width for the handle */\n"
"        height: 14px;  /* Smaller height for the handle */\n"
"        border-radius: 7px;  /* Circular handle with less curve */\n"
"        margin-top: -5px;  /* Adjust handle to be vertically centered */\n"
"        margin-bottom: -5px;\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal:hover {\n"
"        background: #f8f8f8;  /* Slightly lighter background when hovered */\n"
"        border: 2px solid #a0a0a0;  /* Darker border when hovered */\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal:active {\n"
"        background: #f8f8f8;  /* Lighter background when clicked */\n"
"        border: 2px solid #a0a0a0;  /* Darker border when clicked */\n"
"    }")
        self.horizontalSlider.setMinimum(7)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_10.addWidget(self.horizontalSlider)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(0, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.verticalLayout_11.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.play_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_btn.sizePolicy().hasHeightForWidth())
        self.play_btn.setSizePolicy(sizePolicy)
        self.play_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.play_btn.setStyleSheet("#play_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#play_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.play_btn.setText("")
        self.play_btn.setObjectName("play_btn")
        self.horizontalLayout_11.addWidget(self.play_btn)
        spacerItem12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.previous_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_btn.sizePolicy().hasHeightForWidth())
        self.previous_btn.setSizePolicy(sizePolicy)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.previous_btn.setStyleSheet("#previous_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#previous_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.previous_btn.setText("")
        self.previous_btn.setObjectName("previous_btn")
        self.horizontalLayout_11.addWidget(self.previous_btn)
        self.stop_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_btn.sizePolicy().hasHeightForWidth())
        self.stop_btn.setSizePolicy(sizePolicy)
        self.stop_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.stop_btn.setStyleSheet("#stop_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#stop_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.stop_btn.setText("")
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_11.addWidget(self.stop_btn)
        self.next_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_btn.sizePolicy().hasHeightForWidth())
        self.next_btn.setSizePolicy(sizePolicy)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.next_btn.setStyleSheet("#next_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#next_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.next_btn.setText("")
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout_11.addWidget(self.next_btn)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.home_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_btn.sizePolicy().hasHeightForWidth())
        self.home_btn.setSizePolicy(sizePolicy)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_btn.setStyleSheet("#home_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#home_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.home_btn.setText("")
        self.home_btn.setObjectName("home_btn")
        self.horizontalLayout_11.addWidget(self.home_btn)
        self.eq_btn = QtWidgets.QPushButton(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eq_btn.sizePolicy().hasHeightForWidth())
        self.eq_btn.setSizePolicy(sizePolicy)
        self.eq_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.eq_btn.setStyleSheet("#eq_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#eq_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.eq_btn.setText("")
        self.eq_btn.setObjectName("eq_btn")
        self.horizontalLayout_11.addWidget(self.eq_btn)
        spacerItem14 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem16)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.sound_btn = QtWidgets.QPushButton(parent=self.frame_11)
        self.sound_btn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sound_btn.sizePolicy().hasHeightForWidth())
        self.sound_btn.setSizePolicy(sizePolicy)
        self.sound_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.sound_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.sound_btn.setStyleSheet("#sound_btn {\n"
"    background: transparent;  /* Makes the background fully transparent */\n"
"    border: none;            /* Removes the border completely */\n"
"    color: rgb(255, 255, 255); /* Sets the text color (white in this case) */\n"
"    padding: 5px;            /* Adds padding */\n"
"    text-align: center;      /* Centers the text */\n"
"}\n"
"\n"
"#sound_btn:disabled {\n"
"    background: transparent; /* Keeps the background transparent when disabled */\n"
"    border: none;            /* Ensures no border when disabled */\n"
"    color: rgb(255, 255, 255); /* Text color remains white in the disabled state */\n"
"    text-align: center;      /* Centers the text */\n"
"}")
        self.sound_btn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/ui_icons/high-volume.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.sound_btn.setIcon(icon13)
        self.sound_btn.setIconSize(QtCore.QSize(20, 20))
        self.sound_btn.setObjectName("sound_btn")
        self.horizontalLayout_11.addWidget(self.sound_btn)
        self.horizontalSlider_2 = QtWidgets.QSlider(parent=self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(0, 18))
        self.horizontalSlider_2.setStyleSheet("QSlider {\n"
"        background: #f0f0f0;  /* Light grey background, almost white */\n"
"        height: 6px;  /* Slightly thinner slider */\n"
"        border-radius: 6px;  /* Less rounded edges for the whole slider */\n"
"    }\n"
"\n"
"    QSlider::groove:horizontal {\n"
"        border: none;\n"
"        background: #e0e0e0;  /* Light grey groove */\n"
"        height: 6px;\n"
"        border-radius: 6px;  /* Less curved ends for the groove */\n"
"    }\n"
"\n"
"    QSlider::sub-page:horizontal {\n"
"        background: #d0d0d0;  /* Slightly darker grey for the filled part */\n"
"        border-radius: 6px;  /* Less curved ends for the filled part */\n"
"    }\n"
"\n"
"    QSlider::add-page:horizontal {\n"
"        background: #e0e0e0;  /* Same light grey for the unfilled part */\n"
"        border-radius: 6px;  /* Less curved ends for the unfilled part */\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal {\n"
"        background: #ffffff;  /* White handle */\n"
"        border: 2px solid #b0b0b0;  /* Grey border around the handle */\n"
"        width: 14px;  /* Smaller width for the handle */\n"
"        height: 14px;  /* Smaller height for the handle */\n"
"        border-radius: 7px;  /* Circular handle with less curve */\n"
"        margin-top: -5px;  /* Adjust handle to be vertically centered */\n"
"        margin-bottom: -5px;\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal:hover {\n"
"        background: #f8f8f8;  /* Slightly lighter background when hovered */\n"
"        border: 2px solid #a0a0a0;  /* Darker border when hovered */\n"
"    }\n"
"\n"
"    QSlider::handle:horizontal:active {\n"
"        background: #f8f8f8;  /* Lighter background when clicked */\n"
"        border: 2px solid #a0a0a0;  /* Darker border when clicked */\n"
"    }")
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 75)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_11.addWidget(self.horizontalSlider_2)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.mainStack.setCurrentIndex(0)
        self.secondaryStack1.setCurrentIndex(0)
        self.stack2_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logo_label_3.setText(_translate("MainWindow", "  VLC+"))
        self.scan_btn_2.setText(_translate("MainWindow", " Recents"))
        self.ai_btn_2.setText(_translate("MainWindow", " Playlist"))
        self.ai_btn_4.setText(_translate("MainWindow", " Series"))
        self.ai_btn_5.setText(_translate("MainWindow", " Cloud"))
        self.greeting_label.setText(_translate("MainWindow", "Good [Morning/Afternoon/Evening]!"))
        self.label_2.setText(_translate("MainWindow", "Stream"))
        self.stream_url.setPlaceholderText(_translate("MainWindow", "  Link / URL"))
        self.clearURL_btn.setText(_translate("MainWindow", "Clear"))
        self.startStream_btn.setText(_translate("MainWindow", "Go!"))
        self.label.setText(_translate("MainWindow", "Cloud Providers"))
        self.onedrive.setText(_translate("MainWindow", "  OneDrive"))
        self.gdrive.setText(_translate("MainWindow", "  Google Drive"))
        self.box.setText(_translate("MainWindow", "  Box"))
        self.dropbox.setText(_translate("MainWindow", "  DropBox"))
        self.youtube.setText(_translate("MainWindow", "  YouTube"))
        self.localhost.setText(_translate("MainWindow", "  Local Host"))
        self.label_3.setText(_translate("MainWindow", "Select A Provider To Get Started!"))
        self.label_5.setText(_translate("MainWindow", "Nothing New!"))
        self.label_4.setText(_translate("MainWindow", "--:--"))
        self.label_7.setText(_translate("MainWindow", "--:--"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
